<?php

/**
 * Implements hook_views_api().
 */
function cnsb_custom_views_api() {
  return array("version" => "3.0");
}

/*
 * Implements hook_views_query_alter()
 */
function cnsb_custom_views_query_alter(&$view, &$query) {
    // select the view name and display id you'd like to alter
    if ($view->name == 'associated_songs') {
        // the contextual filters are placed in where[0], so change the type of that where group to 'OR'
        $query->where[0]['type'] = "OR";
    }

/*    if ($view->name == 'facet_enabled_song_taxonomy_pages') {
        // the contextual filters are placed in where[0], so change the type of that where group to 'OR'
        $query->where[0]['type'] = "OR";
    }*/
}

/*function cnsb_custom_block_view_alter(&$data, $block) {
  if ($block->region == 'sidebar_first') {
    dpm($data, "Data");  // print form ID to messages
    dpm($block, "Block");  // pretty print array using Krumo to messages
  }
}*/
